### PR TITLE
Blog post open call 2024

### PR DESCRIPTION
**Pull request by yabellini**
Blog post with the dates and the open call for 2024.

### CODE REVIEW

**Comment by beatrizmilz** [comment]
Working on it!

**Comment by beatrizmilz** [comment]
I'm adding the translation to Portuguese and English before publishing, ok?

**Comment by beatrizmilz** [comment]
Yani, something for future PRs: there is no need to add the `docs/` folder, since there is a GitHub Actions that renders the website in 3 langs.

**Comment by yabellini** [comment]
Awesome @beatrizmilz !!! Thanks for reviewing, translating, merging, and the tip for the build! 🙏

**Comment by beatrizmilz** [comment]
> Awesome @beatrizmilz !!! Thanks for reviewing, translating, merging, and the tip for the build! 🙏

You are welcome!!

**Pull request merged**
