### PR TITLE
Registration - Blog post

### LINKED ISSUE #45: Add information that the registration is free
@yabellini 
> La otra cosa, algunas personas estan preguntando costo de registro, como siempre en lo on-line es sin costo.  Solo cobrariamos por los tutoriales.  Pero por ahi podemos agregar esa info en la web.  Voy a ir viendo lo del eventbrite.

### LINKED ISSUE #46: Add post for registration
Like this: http://latinr.org/blog/es/2023-06-08-inscripcion.html
The event is free.
- [ ] Create page on eventbrite @yabellini 
- [ ] Write blogpost on ES
   - [ ] translate to EN  @beatrizmilz  
   - [ ] translate to PT @beatrizmilz

### PR DESCRIPTION
**Pull request by beatrizmilz**
Hi! I wrote the first draft in Spanish. 
When we are ok with it, I can translate the text to Portuguese and English.
- [x] We still need to add the link to event bride. @yabellini 

- [x] After translating, add links in the navbar @beatrizmilz 

Closes #46

### CODE REVIEW

**Comment by yabellini** [comment]
@beatrizmilz eventbrite link: https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?aff=oddtdtcreator

**Comment by beatrizmilz** [comment]
> @beatrizmilz eventbrite link: https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?aff=oddtdtcreator

Thanks Yani!

**Comment by beatrizmilz** [comment]
imagem
@yabellini , I'm not sure if this is meant to be like this, but the platform does not let me register yet :(

**Comment by yabellini** [comment]
I will check it tomorrow but probably is a setup option. 

I also don't have the zoom link and I couldn't add that info yet.

**Pull request merged**
